cc_binary(
  name = "kfs",
  deps = ["@boost//:unordered"],
  srcs = ["kfs.cpp", "kfs.hpp"]
)

cc_binary(
  name = "msl",
  srcs = ["make_struct_lookup.cpp"]
)

cc_binary(
  name = "generate_fasta",
  srcs = ["generate_fasta.cpp"]
)